### ISSUE TITLE
Bug with user options

### ISSUE THREAD

**Issue by Barbercrew3809** [VortexChelmsford/VortexDigitalControl#3]
![image](https://user-images.githubusercontent.com/67389859/87610822-4fbcfd80-c6fe-11ea-9984-83018fe58b1a.png)

if you need log file I will attach it

**Comment by Barbercrew3809** [comment]
update as my previous was informative this box pops up when you log in (I logged in about 4 times to make sure this wasn't a mistake by me)

**Comment by Barbercrew3809** [comment]
[VortexLog.log v2.log](https://github.com/VortexChelmsford/VortexDigitalControl/files/4931259/VortexLog.log.v2.log)

**Comment by maxplayle04** [comment]
Can't reproduce 🤷‍♂️

**Comment by VortexChelmsford** [comment]
Hi, **Brandon**

We're sorry, but we can't reproduce this bug! This could be something to do with your instance, your machine, or a code-related matter. If you could provide us with some steps for how to reproduce this bug, that would be very much appreciated.

With the way we triage bugs, we cannot work on an issue until we can reproduce it. Also, would you be able to elaborate more specifically on what the bug is, what actually happens, and compare it to what you expect to happen.

Thank you,
**Team Vortex**



_Thank you for reporting this issue._
Written by: Stacie Houston, Level 2 Development and Engineering Officer, Vortex Chelmsford Dev Team

**Comment by Barbercrew3809** [comment]
Hello Stacie, 
I have downloaded the latest one and the box is no longer popping up so this might have been an issue with my laptop with the previous version or just an issue with my laptop in general.
